### ISSUE TITLE
Add the issue template

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/companiesdb#154]
Proposed yaml template (draft)

<details>
<summary>Details</summary>

```yml
name: Feature request
description: Report new data or fixing incorrect data from the [Whotracks.me](http://whotracks.me/) database
labels: ["you can create labels and list the corresponding labels here"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        A short description of what information the user can/wants to add or change (new company, tracker, tracker domain; or correct existing info).
        Multiple lines are supported.
      options:
        - label: [If any] Requirements to be fulfilled (a pair of lines "label" + "required". "required" seems to be optional)
          required: true
        - label: AAA (required - "required=true")
          required: true
        - label: BBB (not required)
          required: false

  - type: input
    id: company_name
    attributes:
      label: What is the name of the company?
      description: Enter the official name of the company.
      placeholder: ex. Example Inc.
    validations:
      required: false

  - type: input
    id: company_description
    attributes:
      label: What services does the company provide?
      description: Enter a description of the company. Usually easy to find in the first search results.
      placeholder: ex. https://example.com/
    validations:
      required: false

  - type: input
    id: company_site
    attributes:
      label: What is the address of the company website?
      description: Enter the official website of the company.
      placeholder: ex. https://example.com/
    validations:
      required: false

  - type: input
    id: tracker_name
    attributes:
      label: What is the name of the tracker or service?
      description: Enter the official name of the tracker or the service, if used.
      placeholder: ex. Example Analytics.
    validations:
      required: false

  - type: input
    id: tracker_purpose
    attributes:
      label: What is the purpose of the tracker or service?
      description: Provide a very short description of the tracker or service. It will be used to choose the tracker category.
      placeholder: ex. Ads targeting.
    validations:
      required: false

  - type: input
    id: tracker_site
    attributes:
      label: What is the address of the tracker or service?
      description: Enter the site or URL of the tracker or service. May be the same as the company website.
      placeholder: ex. https://example.com/
    validations:
      required: false

  - type: textarea
    id: tracker_domains
    attributes:
      label: List the domains that are used by the tracker or service.
      description: |
        The tracker domain can be the same as the company website, but there may be more than one.
        Multiple lines are supported.
      value: |
          1. [track.example.com](http://track.example.com/)
          2. [exmpl.xyz](http://exmpl.xyz/)
    validations:
      required: false

  - type: textarea
    id: comments
    attributes:
      label: If there is more information, post it below.
      description: |
        1. Descriction.
        Multiple lines are supported.
      value: |
          1. <comment>
          2. Screenshots
    validations:
      required: false
```

</details>
